# Generated by Django 5.2.4 on 2025-12-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='패키지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='예산')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '패키지',
                'verbose_name_plural': '패키지들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(verbose_name='여행 날짜')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package', verbose_name='패키지')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='장소')),
            ],
            options={
                'verbose_name': '패키지 장소',
                'verbose_name_plural': '패키지 장소들',
                'ordering': ['day', 'order'],
                'unique_together': {('package', 'place', 'day', 'order')},
            },
        ),
        migrations.AddField(
            model_name='package',
            name='places',
            field=models.ManyToManyField(related_name='packages', through='packages.PackagePlace', to='places.place', verbose_name='포함 장소'),
        ),
    ]
