# Generated by Django 5.2.4 on 2025-12-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='장소명')),
                ('category', models.CharField(choices=[('tourist', '관광지'), ('restaurant', '맛집'), ('hotel', '숙박'), ('activity', '액티비티'), ('shopping', '쇼핑')], max_length=20, verbose_name='카테고리')),
                ('address', models.CharField(max_length=300, verbose_name='주소')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='평점')),
                ('average_price', models.IntegerField(blank=True, null=True, verbose_name='평균 가격')),
                ('price_level', models.IntegerField(blank=True, null=True, verbose_name='가격 레벨 (1-5)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='태그')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '장소',
                'verbose_name_plural': '장소들',
                'ordering': ['-created_at'],
            },
        ),
    ]
